- _posts/es/0200-12-24-papers.md
We were using "Walking Papers" in previous versions and now, we have
migrated to "Field Papers". That's why the docs has to be updated
also.
> Update Spanish translation to "Field Papers" (#232)

- _posts/en/beginner/0200-12-28-start-id.md
- _posts/en/beginner/0200-12-29-start-id.md
Followed althio's advice on this one.
> added 0200-12-28-start-id.md file for issue276

- _layouts/default.html
This should just remove the Google Analytics tracking javascript and replace it with the piwik tracking javascript. It seems to work based on my local testing.
> Replaces GoogleAnalytics with Piwik tracking code

- files/sample.osm
upload='false' to provide additional warning
related to #335
> upload='false' in sample.osm

- _posts/en/beginner/0200-12-28-start-josm.md
This came up on the HOT mailing list (https://lists.openstreetmap.org/pipermail/hot/2015-May/008499.html), thought I'd add to LearnOSM
> Added wiki link for Mac users with outdated java

- _posts/en/mobile-mapping/0900-12-29-osmand.md
Part of #349
* Emphasis on online/offline, less so on vector vs raster maps
* Adds google play store logo, link which is a lot easier to recognize than the previous text. App Store links for iOS version also possible to add later
* Pushes User Interface stuff up further, Configuration after that so that the idea of the app is explained better, as a gentle lead in to "how do I get data and take this thing offline"
> Rearrange content to help users start faster

- _posts/sw/0200-12-30-introduction.md
- _posts/sw/0200-12-31-beginner.md
I wasn't sure of the folder name to use - got my result from http://en.wikipedia.org/wiki/Swahili_language but feel free to change if I've got it wrong. Language is not my strong point!
> Adding section for Kiswahili as Swahili

- _layouts/default.html
> Revert "Patch kiswahili"

- _layouts/default.html
Add sw-Kiswahili and sort languages
Keep English first and sort by code
> Add sw-Kiswahili and sort languages

- _posts/en/editing/Submitting bugs or ideas
Saw the message on hot list, put this together quickly. I'm creating a new page, but maybe you'd want to integrate the content into an existing one.
I also have two screenshots, but I don't know how to get the images into this project. If you let me know, I can upload and integrate into the page.
> Create a page: how to submit bugs/ideas for iD

- _posts/en/mobile-mapping/0900-12-20-osmand2.md
The main OsmAnd app is available for iOS.
> Link to iOS app

- CNAME
- _posts/bi/osm-data/0600-12-13-osm-in-qgis.md
- _posts/es/osm-data/0600-12-13-osm-in-qgis.md
- _posts/fr/osm-data/0600-12-13-osm-in-qgis.md
- _posts/ja/osm-data/0600-12-13-osm-in-qgis.md
> links to qgis-in-osm - all languages

- _posts/sw/beginner/0200-12-05-glossary.md
- _posts/sw/beginner/0200-12-23-id-editor.md
- _posts/sw/beginner/0200-12-27-start-osm.md
- _posts/sw/beginner/0200-12-31-beginner.md
- _posts/sw/coordination/0500-12-06-remote-mapping.md
- _posts/sw/josm/1900-12-09-editing-with-josm.md
I have translated the coordination chapter and made minor edits to a few other chapters
> Translating LearnOSM to Swahili

- _posts/de/josm/1900-12-09-editing-with-josm.md
Not that much. Just some typographical and one or two grammatical errors fixed.
> German typographical and grammatical fixes.

- _config.yml
Hello all! 
This PR closes #492 by upgrading the deprecated settings. It also tries to explain the configuration settings in `_config.yml` by adding links and comments that describe parts of this file. Finally, I added some more prose configuration settings.
I tested the site locally and it looks like it's working fine. 
I haven't tested the Prose.io tool though. @Nick-Tallguy Are the site's posts supposed to be editable with Prose.io?
> Upgrade learnosm's config file

- _posts/en/osm-data/0600-12-30-data-overview.md
changed Quantom GIS references to QGIS
> Quantom GIS is now simply known as QGIS

- _posts/en/0200-12-27-start-osm.md
follows https://github.com/openstreetmap/iD/issues/4111
> add link to iD walkthrough

- _posts/en/0100-01-01-index.md
> missing full stop

- _layouts/default.html
- tracking-v1.js
We recently switched over to a new website tracking system, (Piwik is now called Matomo). We are also working on getting all of our sites GDPR compliant. This update will implement a form that pops up on the bottom of the page that allows users to opt-out of tracking.
> Update analytics tracking code and add optout form

- _posts/en/0900-07-20-vespucci_en.md
Nick emailed me that the images in Vespucci Editor are not showing on the learnosm site. My bad, I named the images .png but I referenced them in the .md file as .PNG.
> Edited Vespucci .md so images will show on the learnosm site

- _posts/id/0450-10-05-saving_id.md
- _posts/id/0450-12-27-id-imag_id.md
correct errors from translation of image names
> amendments to id language modules in hot-tips - correcting errors

- all-translation.json
> fixed typo breaking search in es, fa

- style.css
**Before**
**After**
----
**Before**
**After**
> Improve margins and numbers on lists

- _posts/en/0900-12-30-mobile_mapping_en.md
> assume that smartphone has GPS, fixes #638

- _posts/en/1900-12-21-start-josm_en.md
> do not mention CDs/USBs, Internet Explorer -> Edge

- _posts/en/0500-10-24-tm-admin_en.md
Reviewing and updating given new onboarding process and Tasking Manager updates since last changes. Have got down to **Entities to Map** row 220, saving for now, will continue next week.
> Complete overhaul of 0500-10-24-tm-admin_en.md

- _posts/en/0200-12-23-id-editor_en.md
right now "de facto" is not needed as Potlatch died
BTW, it would be nice to linkify JOSM but I have not figured out how to do this
> simplify text

- _posts/en/0200-12-05-glossary_en.md
Removed the redundant *describe* word in the *Tag* definition.
> Update the glossary en
